### ISSUE TITLE
Setting up ingress for dex to communicate with Argo-workflows

### ISSUE THREAD

**Issue by KEdore** [dexidp/helm-charts#133]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/helm-charts/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/helm-charts/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/helm-charts/issues/new/choose) without success.

### Chart

dex

### Version

0.17.1

### Expected Behavior

I expect Dex and Argo Workflows to communicate with each other within the same EKS cluster. Both services have ingress configurations set up, but Argo Workflows cannot recognize Dex through the ingress URL.

### Actual Behavior

Actual Behavior:
Despite having ingress set up for both Dex and Argo Workflows, Argo Workflows is unable to communicate with Dex. It throws the following error:
```
time="2024-06-10T10:25:41.991Z" level=info msg="not enabling pprof debug endpoints"
time="2024-06-10T10:25:41.992Z" level=info authModes="[sso]" baseHRef=/ managedNamespace= namespace=clearing secure=false ssoNamespace=clearing
time="2024-06-10T10:25:41.992Z" level=warning msg="You are running in insecure mode. Learn how to enable transport layer security: https://argo-workflows.readthedocs.io/en/release-3.5/tls/"
Error: Get "https://dex-tester.dev/.well-known/openid-configuration": dial tcp: lookup dex.tester.dev on 172.20.0.10:53: no such host
```

### Steps To Reproduce

- Deploy Dex and Argo Workflows on an EKS cluster.
- Set up ingress for both Dex and Argo Workflows.
- Attempt to configure Argo Workflows to use Dex for SSO authentication with ingress URL.

### Additional Information

I have verified that the DNS resolution within the cluster is working correctly for other services, but dex.tester.dev cannot be resolved. The ingress for Dex is accessible externally, but Argo Workflows cannot seem to communicate with it.

I suspect there might be an issue with the health check path or the ingress configuration that is preventing Argo Workflows from resolving Dex.

Any help or guidance on resolving this issue would be greatly appreciated.

### Values

```yaml
ingress:
    # -- Enable [ingress](https://kubernetes.io/docs/concepts/services-networking/ingress/).
    enabled: true

    # -- Ingress [class name](https://kubernetes.io/docs/concepts/services-networking/ingress/#ingress-class).
    className: "alb"

    # -- Annotations to be added to the ingress.
    annotations: {
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]',
      alb.ingress.kubernetes.io/target-type: "ip",
      alb.ingress.kubernetes.io/scheme: "internet-facing",
      alb.ingress.kubernetes.io/healthcheck-path: "/healthz/ready",
      alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}',
      alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:eu-west-2:some-arn",
    }
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"

    # -- Ingress host configuration.
    # @default -- See [values.yaml](values.yaml).
    hosts:
      - host: dex.tester.dev
        paths:
          - path: /
            pathType: Prefix
```
