### ISSUE TITLE
Invalid servicemonitor.yaml generated due to newline

### ISSUE THREAD

**Issue by sherif-fanous** [dexidp/helm-charts#148]
### Preflight Checklist

- [x] I agree to follow the [Code of Conduct](https://github.com/dexidp/helm-charts/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/dexidp/helm-charts/issues) for an issue that matches the one I want to file, without success.
- [x] I am not looking for support or already pursued the available [support channels](https://github.com/dexidp/helm-charts/issues/new/choose) without success.

### Chart

dex

### Version

0.21.0

### Expected Behavior

Valid YAML generated for all templates.

### Actual Behavior

The last release of the dex chart (0.21.0) introduced a bug in `servicemonitor.yaml` where a newline is added after `namespace:`

This is the generated YAML

```yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dex
  namespace: 
dex
  labels:
    helm.sh/chart: dex-0.21.0
    app.kubernetes.io/name: dex
    app.kubernetes.io/instance: dex
    app.kubernetes.io/version: "2.41.1"
    app.kubernetes.io/managed-by: Helm
spec:
  endpoints:
    - port: telemetry
      path: /metrics
      honorLabels: false
  jobLabel: dex
  selector:
    matchLabels:
      app.kubernetes.io/name: dex
      app.kubernetes.io/instance: dex
  namespaceSelector:
    matchNames:
      - dex
```

As a result `helm` errors out with `Error: YAML parse error on dex/templates/servicemonitor.yaml: error converting YAML to JSON: yaml: line 7: could not find expected ':'`

### Steps To Reproduce

Try to generate helm templates with `.serviceMonitor.enabled` set to `true`

### Values

```yaml
---
configSecret:
  create: false
  name: dex

serviceMonitor:
  enabled: true
```
