### ISSUE TITLE
Use Role instead of ClusterRole for dex custom resources access rights

### ISSUE THREAD

**Issue by nabokihms** [dexidp/helm-charts#21]
This is a minor isolation issue. 

Custom resources from API group `dex.coreos.com` are namespaced by their nature. Dex instance in Kubernetes cluster only needs to react to resources from its namespace. 

So, it is better to use `Role` to give dex rights as below: 
```yaml
- apiGroups: ["dex.coreos.com"]
  resources: ["*"]
  verbs: ["*"]
```
