### ISSUE TITLE
Option to create a secret when using the Google connector.

### ISSUE THREAD

**Issue by vanneback** [dexidp/helm-charts#23]
When using the Google [connector](https://dexidp.io/docs/connectors/google/) you have to set the `serviceAccountFilePath` in the config. When installing inside the cluster this will have to exists in a secret that we can mount. It would be great if there is an option in the helm chart for this instead of having to create it before using the helm chart.

Does this seem like a reasonable request? If so I could probably send in a PR for it.

**Comment by sagikazarmark** [comment]
Honestly, it feels like something that the user should do before installing the chart. You can have multiple google connectors configured in a single Dex instance, so there is no clean and generic way to do it in the chart (at least one that I see).

**Comment by TheRealNoob** [comment]
@sagikazarmark What about an `extraSecrets" []` approach?  Alternatively you could do `extraManifests: []` which is more generic and thus flexible, but requires users to handle the base64 encoding themselves, unless you pipe it through `tpl` and they define `{{ base64enc ... }}`.

Example [extraSecrets](https://github.com/prometheus-community/helm-charts/blob/78952f92d753338c57b06ef6c9be1fcd94039e14/charts/kube-prometheus-stack/templates/prometheus/extrasecret.yaml) and [extraManifests](https://github.com/prometheus-community/helm-charts/blob/78952f92d753338c57b06ef6c9be1fcd94039e14/charts/kube-prometheus-stack/templates/extra-objects.yaml) implementations.

```yaml
extraSecrets:
  - name: dex-google-serviceAccount-credentials
    type: Opaque
    data:
      project1.json: |
        SuperSecetJSONCredentials
```

```yaml
volumes:
  - name: google-serviceAccount-credentials
    secret:
      secretName: dex-google-serviceAccount-credentials

volumeMounts:
  - name: google-serviceAccount-credentials
    readOnly: true
    mountPath: /tmp/google-serviceAccount-credentials

config:
  connectors:
    - type: google
      config:
        serviceAccountFilePath: /tmp/google-serviceAccount-credentials/project1.json
```
