### ISSUE TITLE
missing HTTPS service port in values.yaml

### ISSUE THREAD

**Issue by bsctl** [dexidp/helm-charts#37]
Missing HTTPS service port in `values.yaml` file. It's referenced into templates but not defined into values file.

```yaml
service:
  annotations: {}
  type: ClusterIP
  ports:
    http:
      # -- HTTP service port
      port: 5556
      # -- (int) HTTP node port (when applicable)
      nodePort: 32080
    https: # <<< THIS!
      # -- HTTPS service port
      port: 5554
      # -- (int) HTTPS node port (when applicable)
      nodePort: 32443
    grpc:
      # -- gRPC service port
      port: 5557
      # -- (int) gRPC node port (when applicable)
      nodePort:
```
