### ISSUE TITLE
add commonLabels and commonAnnotations

### ISSUE THREAD

**Issue by ecthelion77** [dexidp/helm-charts#65]
### Preflight Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/dexidp/helm-charts/blob/master/.github/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/dexidp/helm-charts/issues) for an issue that matches the one I want to file, without success.

### Problem Description

No possibilities to define labels and annotation for resources in chart.

### Proposed Solution

Best practice for helm chart development consists to add following metadata definitions on each template :
```yaml
  labels:
    app.kubernetes.io/name: {{ template "dex.name" . }}
    helm.sh/chart: {{ template "dex.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
```
